language: node_js
node_js:
- 5.2.0
install:
- npm install
script:
- webpack
sudo: false
before_deploy:
- npm-prepublish --verbose
deploy:
- provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_API_KEY"
  on:
    tags: true
env:
  global:
  - secure: l+jrkAs5ovRFYbR/meEa3u6QONEdtoJBWGgR9ZvpYrSpSNUaiHohkUBv6SfhrQgr9nkmEPQRGBsWDodpv7MgJbDbrKLPKNCaLH22k5LK/m+w+2mgNDMi+U/9KUwgNkIMAVjzHUJHYKoLBTehVIaNqHMLk63lPt3wZJF30+2YAdJBKDUAlpAaH5snLqVvuPQJcbLJufvJnNPmTByEtdudz3pVGWhbJSWLr7siYAy+eEyZeqhdFDIbGjgRCn8z9klHj66M8J8u9/VD2ZqlD9k8WQKkbWy/AhvSJ1cR6cAeVy+wYgjphoilmf3dGv2pD5KiTA3mUz6sqz1+eaBe8qe76ufy6kUurjfUaV6noPhR6qhFnWoJffIkKS5j5xrzxgFrcqzQ9gASeV3BDLjm4SYI4VF9XCBxrGJz3VLP377o74SqGfzZ7681em+Nv20YgdeDSZZWG8bWCO05On0SeVqyTWHF2TiSXytMvoXtm1wVWZGnC1ftHHfb1VqKPGA+/Srx5gazpb+Qe1jgUFEkWJSiKQSs1znu1q38kCQ2xsPQIejefcIY4kg/DVz+oqvrXW7uWPO8YY/y8JVX8IieVMBDmIspsodNlpUYz1l2HaTyVV2sIhMpLWZLiT7I6/YNFjZ1sLzFf2Ne2Hhd9IRZW2JvNuUB4dJ252dmYp0qD4ZueVo=
  - secure: rzQ0Fvg6PA2/TvyfOnjOr+7yF+eUL1xV7R/PtjuyYDkRPaz8cLr78LswJZY7AjuVeRk55fyAWKLHctkiC6zwOP17yu2RjbX01nQx66f2gIvpUzTiyKpgQlpMtxPSBsi4VnSmDQCJVFgAj/yOvbjiLcJiKEixbMXkXvaJEsaeVTOpuBz1qFObf9q93kfnkD7qyZkLVjj4TdOLf93OseH9UQztVC64dZcwNely2km/w8M/c/DQDodUC597qbAg8UhWr2i6MU1elz/TkJAJ8vhbYYcXKIZEl3gm6OruwPj83qzDKeRfhH9y4gwp9aregGgigfpwyQ6KCw90QJ3+0//FGfgQjmhcJdta9vXP4dXgPbB8lqHYuL3QO9XsAgXhhnjpTkfVvOKoM8loNSd6WH9uPsVSHoLtz+w7d48GwLAxzbs2cTySvhMwQjBz+RpQGNVuXxdW5cxDzQLFw8utgmY5yy/EOjKXJpuS7e7dLN2EPulfdUtSy9UMB2UjgIJwi6vexxNQR/r39z5epECv4++ipJfbn6jYJLge4Twu4NCd4YvCSQ74+D4uwfXtRocmp+p8i7S7Pa8x54QXikjQmlDmoCgWButlFYV8MQDY4UbQiKydT1J4KqOBtrLd68a48QDq9ttrjjqEy+8ntmiY05vPJO30puGc5J3c46OYTXFyC58=
