require 'zepto/zepto.min'
require 'angular'
require './scripts/home'
require './views/home'
require './styles/home'
require './images/project-custom.svg'

require '../node_modules/font-awesome/fonts/fontawesome-webfont.eot'
require '../node_modules/font-awesome/fonts/fontawesome-webfont.svg'
require '../node_modules/font-awesome/fonts/fontawesome-webfont.ttf'
require '../node_modules/font-awesome/fonts/fontawesome-webfont.woff'
require '../node_modules/font-awesome/fonts/fontawesome-webfont.woff2'
require '../node_modules/font-awesome/css/font-awesome.css'